-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0806
--   at:        2019-05-02 17:45:13 SRET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
set echo on
spool ./airtnt_schema_output.txt

DROP SEQUENCE "Activity-Charge_activity_code";

DROP SEQUENCE "Cost-Centre_costcentre_code";

DROP SEQUENCE customer_cust_id_seq;

DROP SEQUENCE house_house_code_seq;

DROP SEQUENCE housekeeper_keeper_id_seq;

DROP SEQUENCE "Item-Description_item_code_SEQ";

DROP SEQUENCE room_room_no_seq;

DROP SEQUENCE "Tour-Guide_tour_guide_id_SEQ";

DROP SEQUENCE "Tour-Specialisation_tour_guide";


DROP TABLE activity CASCADE CONSTRAINTS;

DROP TABLE "Activity-Charge" CASCADE CONSTRAINTS;

DROP TABLE "Additional-Item" CASCADE CONSTRAINTS;

DROP TABLE "Check-In" CASCADE CONSTRAINTS;

DROP TABLE "Cost-Centre" CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE guide_specialisation CASCADE CONSTRAINTS;

DROP TABLE house CASCADE CONSTRAINTS;

DROP TABLE "House-Assignment" CASCADE CONSTRAINTS;

DROP TABLE housekeeper CASCADE CONSTRAINTS;

DROP TABLE "Item-Description" CASCADE CONSTRAINTS;

DROP TABLE room CASCADE CONSTRAINTS;

DROP TABLE "Tour-Guide" CASCADE CONSTRAINTS;

DROP TABLE "Tour-Specialisation" CASCADE CONSTRAINTS;

CREATE TABLE activity (
    req_by           VARCHAR2(50) NOT NULL,
    perf_by          VARCHAR2(50),
    perf_on          DATE NOT NULL,
    date_time        DATE NOT NULL,
    cust_id          NUMBER(10) NOT NULL,
    activity_code    NUMBER(10) NOT NULL,
    tour_guide_id    NUMBER,
    tour_guide_id1   NUMBER NOT NULL
);

COMMENT ON COLUMN activity.req_by IS
    'activity requested by the tourguide';

COMMENT ON COLUMN activity.perf_by IS
    'activity perfomed by tourguide';

COMMENT ON COLUMN activity.perf_on IS
    'the date activity was performed';

COMMENT ON COLUMN activity.date_time IS
    'date and time of check in';

COMMENT ON COLUMN activity.cust_id IS
    'id of the customer';

COMMENT ON COLUMN activity.activity_code IS
    'code for a particular activity';

COMMENT ON COLUMN activity.tour_guide_id IS
    'id number tour the tourguide';

COMMENT ON COLUMN activity.tour_guide_id1 IS
    'id number tour the tourguide';

ALTER TABLE activity
    ADD CONSTRAINT activity_pk PRIMARY KEY ( date_time,
                                             cust_id,
                                             activity_code );

CREATE TABLE "Activity-Charge" (
    activity_code          NUMBER(10) NOT NULL,
    activity_name          VARCHAR2(50) NOT NULL,
    activity_description   VARCHAR2(50) NOT NULL,
    time_required          NUMBER(10) NOT NULL,
    cust_charge            NUMBER(10,2) NOT NULL
);

COMMENT ON COLUMN "Activity-Charge".activity_code IS
    'code for a particular activity';

COMMENT ON COLUMN "Activity-Charge".activity_name IS
    'name of the activity';

COMMENT ON COLUMN "Activity-Charge".activity_description IS
    'description of the activity';

COMMENT ON COLUMN "Activity-Charge".time_required IS
    'time required for the activity';

COMMENT ON COLUMN "Activity-Charge".cust_charge IS
    'charge to the customer';

ALTER TABLE "Activity-Charge" ADD CONSTRAINT "Activity-Charge_PK" PRIMARY KEY ( activity_code );

CREATE TABLE "Additional-Item" (
    quantity        NUMBER(10),
    date_time       DATE NOT NULL,
    cust_id         NUMBER(10) NOT NULL,
    activity_code   NUMBER(10) NOT NULL,
    item_code       NUMBER(10) NOT NULL,
    item_charge     NUMBER(10,2),
    total_charge    NUMBER(10,2)
);

ALTER TABLE "Additional-Item" ADD CONSTRAINT chk_quantity CHECK ( quantity > 0 );

COMMENT ON COLUMN "Additional-Item".quantity IS
    'quantity of items used';

COMMENT ON COLUMN "Additional-Item".date_time IS
    'date and time of check in';

COMMENT ON COLUMN "Additional-Item".cust_id IS
    'id of the customer';

COMMENT ON COLUMN "Additional-Item".activity_code IS
    'code for a particular activity';

COMMENT ON COLUMN "Additional-Item".item_charge IS
    'item charge ';

COMMENT ON COLUMN "Additional-Item".total_charge IS
    'total charge of all the items';

ALTER TABLE "Additional-Item"
    ADD CONSTRAINT "Additional-Item_PK" PRIMARY KEY ( date_time,
                                                      cust_id,
                                                      activity_code,
                                                      item_code );

CREATE TABLE "Check-In" (
    date_time            DATE NOT NULL,
    checkout_date_time   DATE NOT NULL,
    cust_id              NUMBER(10) NOT NULL,
    tour_guide_id        NUMBER NOT NULL
);

COMMENT ON COLUMN "Check-In".date_time IS
    'date and time of check in';

COMMENT ON COLUMN "Check-In".checkout_date_time IS
    'customer checkout date and time';

COMMENT ON COLUMN "Check-In".cust_id IS
    'id of the customer';

COMMENT ON COLUMN "Check-In".tour_guide_id IS
    'id number tour the tourguide';

ALTER TABLE "Check-In" ADD CONSTRAINT "Check-In_PK" PRIMARY KEY ( date_time,
                                                                  cust_id );

CREATE TABLE "Cost-Centre" (
    costcentre_code    NUMBER(10) NOT NULL,
    costcentre_title   VARCHAR2(50) NOT NULL,
    admin_name         VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN "Cost-Centre".costcentre_code IS
    'unique code for cost centre';

COMMENT ON COLUMN "Cost-Centre".costcentre_title IS
    'title of the cost centre';

COMMENT ON COLUMN "Cost-Centre".admin_name IS
    'name of the admin incharge';

ALTER TABLE "Cost-Centre" ADD CONSTRAINT "Cost-Centre_PK" PRIMARY KEY ( costcentre_code );

CREATE TABLE customer (
    cust_id           NUMBER(10) NOT NULL,
    cust_firstname    VARCHAR2(50) NOT NULL,
    cust_lastname     VARCHAR2(50) NOT NULL,
    street            VARCHAR2(50) NOT NULL,
    city              VARCHAR2(50) NOT NULL,
    zip_code          NUMBER(10) NOT NULL,
    country           VARCHAR2(50) NOT NULL,
    d_o_b             DATE NOT NULL,
    mob_no            CHAR(10) NOT NULL,
    user_email        VARCHAR2(50) NOT NULL,
    pan_no            NUMBER(5) NOT NULL,
    emergency_phone   CHAR(10)
);

COMMENT ON COLUMN customer.cust_id IS
    'id of the customer';

COMMENT ON COLUMN customer.cust_firstname IS
    'firstname of the customer';

COMMENT ON COLUMN customer.cust_lastname IS
    'customer lastname';

COMMENT ON COLUMN customer.street IS
    'street address';

COMMENT ON COLUMN customer.city IS
    'city';

COMMENT ON COLUMN customer.zip_code IS
    'the zipcode';

COMMENT ON COLUMN customer.country IS
    'the country of the customer';

COMMENT ON COLUMN customer.d_o_b IS
    'dte of birth';

COMMENT ON COLUMN customer.mob_no IS
    'mobile number';

COMMENT ON COLUMN customer.user_email IS
    'email of the user';

COMMENT ON COLUMN customer.pan_no IS
    'last 4 digits of the card';

COMMENT ON COLUMN customer.emergency_phone IS
    'emergency contact phone number';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE guide_specialisation (
    description   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN guide_specialisation.description IS
    'description of the guide specialisation';

ALTER TABLE guide_specialisation ADD CONSTRAINT guide_specialisation_pk PRIMARY KEY ( description );

CREATE TABLE house (
    house_code   NUMBER(10) NOT NULL,
    house_name   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN house.house_code IS
    'house number of a particular house';

COMMENT ON COLUMN house.house_name IS
    'house name of the house';

ALTER TABLE house ADD CONSTRAINT house_pk PRIMARY KEY ( house_code );

CREATE TABLE "House-Assignment" (
    date_assigned   DATE NOT NULL,
    date_comp       DATE NOT NULL,
    house_code      NUMBER(10) NOT NULL,
    keeper_id       NUMBER(10) NOT NULL
);

COMMENT ON COLUMN "House-Assignment".date_assigned IS
    'date for which the keeper is assigned';

COMMENT ON COLUMN "House-Assignment".date_comp IS
    'date when the cleaning is completed';

COMMENT ON COLUMN "House-Assignment".house_code IS
    'house number of a particular house';

COMMENT ON COLUMN "House-Assignment".keeper_id IS
    'keeper number assigned to a keeper';

ALTER TABLE "House-Assignment" ADD CONSTRAINT "House-Assignment_PK" PRIMARY KEY ( house_code,
                                                                                  keeper_id );

CREATE TABLE housekeeper (
    keeper_id          NUMBER(10) NOT NULL,
    keeper_firstname   VARCHAR2(50) NOT NULL,
    keeper_lastname    VARCHAR2(50) NOT NULL,
    keeper_phone       CHAR(10) NOT NULL,
    police_cert        VARCHAR2(50),
    bankruptcy_check   CHAR(1) NOT NULL
);

COMMENT ON COLUMN housekeeper.keeper_id IS
    'keeper number assigned to a keeper';

COMMENT ON COLUMN housekeeper.keeper_firstname IS
    'firstname of the keeper';

COMMENT ON COLUMN housekeeper.keeper_lastname IS
    'lastname of the keeper';

COMMENT ON COLUMN housekeeper.keeper_phone IS
    'phone number of the keeper';

COMMENT ON COLUMN housekeeper.police_cert IS
    'police certificate of the keeper';

COMMENT ON COLUMN housekeeper.bankruptcy_check IS
    'boolean check for the bankruptcy';

ALTER TABLE housekeeper ADD CONSTRAINT housekeeper_pk PRIMARY KEY ( keeper_id );

CREATE TABLE "Item-Description" (
    item_code          NUMBER(10) NOT NULL,
    item_description   VARCHAR2(50) NOT NULL,
    costcentre_code    NUMBER(10) NOT NULL
);

COMMENT ON COLUMN "Item-Description".item_description IS
    'description about the item';

COMMENT ON COLUMN "Item-Description".costcentre_code IS
    'unique code for cost centre';

ALTER TABLE "Item-Description" ADD CONSTRAINT "Item-Description_PK" PRIMARY KEY ( item_code );

CREATE TABLE room (
    room_no        NUMBER(10) NOT NULL,
    telephone_no   CHAR(10),
    room_type      VARCHAR2(50) NOT NULL,
    empty_rooms    NUMBER(10) NOT NULL,
    house_code     NUMBER(10) NOT NULL,
    date_time      DATE NOT NULL,
    cust_id        NUMBER(10) NOT NULL
);

COMMENT ON COLUMN room.room_no IS
    'room number in each house';

COMMENT ON COLUMN room.telephone_no IS
    'telephone number of the room ';

COMMENT ON COLUMN room.room_type IS
    'type of room';

COMMENT ON COLUMN room.empty_rooms IS
    'number of empty rooms';

COMMENT ON COLUMN room.house_code IS
    'house number of a particular house';

COMMENT ON COLUMN room.date_time IS
    'date and time of check in';

COMMENT ON COLUMN room.cust_id IS
    'id of the customer';

ALTER TABLE room ADD CONSTRAINT room_pk PRIMARY KEY ( room_no,
                                                      house_code );

CREATE TABLE "Tour-Guide" (
    tour_guide_id     NUMBER NOT NULL,
    guide_firstname   VARCHAR2(50) NOT NULL,
    guide_lastname    VARCHAR2(50) NOT NULL,
    phone_no          CHAR(10) NOT NULL,
    instagram_id      VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN "Tour-Guide".tour_guide_id IS
    'id number tour the tourguide';

COMMENT ON COLUMN "Tour-Guide".guide_firstname IS
    'firstname of the tourguide';

COMMENT ON COLUMN "Tour-Guide".guide_lastname IS
    'lastname of the tourguide';

COMMENT ON COLUMN "Tour-Guide".phone_no IS
    'tourguide phone number';

COMMENT ON COLUMN "Tour-Guide".instagram_id IS
    'instagram id of the tour guide';

ALTER TABLE "Tour-Guide" ADD CONSTRAINT "Tour-Guide_PK" PRIMARY KEY ( tour_guide_id );

CREATE TABLE "Tour-Specialisation" (
    tour_guide_id   NUMBER NOT NULL,
    description     VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN "Tour-Specialisation".tour_guide_id IS
    'id number tour the tourguide';

COMMENT ON COLUMN "Tour-Specialisation".description IS
    'description of the guide specialisation';

ALTER TABLE "Tour-Specialisation" ADD CONSTRAINT "Tour-Specialisation_PK" PRIMARY KEY ( tour_guide_id,
                                                                                        description );

ALTER TABLE "Additional-Item"
    ADD CONSTRAINT "activity-item" FOREIGN KEY ( date_time,
                                                 cust_id,
                                                 activity_code )
        REFERENCES activity ( date_time,
                              cust_id,
                              activity_code );

ALTER TABLE "Item-Description"
    ADD CONSTRAINT "centre-description" FOREIGN KEY ( costcentre_code )
        REFERENCES "Cost-Centre" ( costcentre_code );

ALTER TABLE activity
    ADD CONSTRAINT "charge-activity" FOREIGN KEY ( activity_code )
        REFERENCES "Activity-Charge" ( activity_code );

ALTER TABLE activity
    ADD CONSTRAINT "checkin-activity" FOREIGN KEY ( date_time,
                                                    cust_id )
        REFERENCES "Check-In" ( date_time,
                                cust_id );

ALTER TABLE room
    ADD CONSTRAINT "checkin-room" FOREIGN KEY ( date_time,
                                                cust_id )
        REFERENCES "Check-In" ( date_time,
                                cust_id );

ALTER TABLE "Check-In"
    ADD CONSTRAINT "customer-checkin" FOREIGN KEY ( cust_id )
        REFERENCES customer ( cust_id );

ALTER TABLE "Additional-Item"
    ADD CONSTRAINT "desc-item" FOREIGN KEY ( item_code )
        REFERENCES "Item-Description" ( item_code );

ALTER TABLE activity
    ADD CONSTRAINT "guide-activity" FOREIGN KEY ( tour_guide_id )
        REFERENCES "Tour-Guide" ( tour_guide_id );

ALTER TABLE "Tour-Specialisation"
    ADD CONSTRAINT "guide-specialisation" FOREIGN KEY ( tour_guide_id )
        REFERENCES "Tour-Guide" ( tour_guide_id );

ALTER TABLE "Tour-Specialisation"
    ADD CONSTRAINT "guide-specialisationv2" FOREIGN KEY ( description )
        REFERENCES guide_specialisation ( description );

ALTER TABLE "House-Assignment"
    ADD CONSTRAINT "house-houseassignment" FOREIGN KEY ( house_code )
        REFERENCES house ( house_code );

ALTER TABLE room
    ADD CONSTRAINT "house-room" FOREIGN KEY ( house_code )
        REFERENCES house ( house_code );

ALTER TABLE "House-Assignment"
    ADD CONSTRAINT "keeper-assignment" FOREIGN KEY ( keeper_id )
        REFERENCES housekeeper ( keeper_id );

ALTER TABLE activity
    ADD CONSTRAINT "tour-activity" FOREIGN KEY ( tour_guide_id1 )
        REFERENCES "Tour-Guide" ( tour_guide_id );

ALTER TABLE "Check-In"
    ADD CONSTRAINT "tourguide-checkin" FOREIGN KEY ( tour_guide_id )
        REFERENCES "Tour-Guide" ( tour_guide_id );

CREATE SEQUENCE "Activity-Charge_activity_code" START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE "Cost-Centre_costcentre_code" START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE customer_cust_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE house_house_code_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE housekeeper_keeper_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE "Item-Description_item_code_SEQ" START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE room_room_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE "Tour-Guide_tour_guide_id_SEQ" START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE "Tour-Specialisation_tour_guide" START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          9
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
